logging:
  pattern:
    console: "[%clr(%-5level){magenta}] - %cyan(%logger{15}) - %clr(%msg%n)"
  level:
    org.mitmit: DEBUG
    org.springframework: FATAL
spring:
  output:
    ansi:
      enabled: always
sqqm:
  exclude-recipe-type:
    - NONE
    - SOUPE